# Generated by Django 5.2.4 on 2025-07-16 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secureblog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
    ]
